### ISSUE TITLE
Add setting to change tray icon font size

### ISSUE THREAD

**Issue by MR-MK47** [soleon/Percentage#12]
![image](https://github.com/user-attachments/assets/9c7d171a-a0cd-49bb-aba0-ffe038689c78)
just look how small the size is, and please give the option to change size

**Comment by soleon** [comment]
@MR-MK47 thank you for reporting the issue. Do you mind sharing the font you set for the icon, and your display scaling settings? Does restarting the app (right click icon > exit) changes anything?

**Comment by SenorQueso1** [comment]
I have the same issue, changing the font, making it bold, or making it italicized didn't fix anything. The only thing that work for me was restarting the app. My display scaling is 200x and my display resolution is 2256 x  1504, both of which are the "(recommended)" set by windows.

**Comment by soleon** [comment]
I have release version [2.1.3](https://github.com/soleon/Percentage/releases/tag/2.1.3) with the setting to change the tray icon font size. It should be available in the Microsoft Store already.

![image](https://github.com/user-attachments/assets/035e0131-b257-4237-98c3-73d199f1b18e)

Note that the tray icon region is limited by Windows system itself so if you set the font size to too large, it gets cut off by the system like this:

![image](https://github.com/user-attachments/assets/866e4fd4-255b-4536-8edf-70d7c79aecb6)

**Comment by soleon** [comment]
Closing this one. It is duplicated with issue #6.
