### ISSUE TITLE
Settings resetting every start up

### ISSUE THREAD

**Issue by lucaorla2000** [soleon/Percentage#14]
After the update, every time I turn on the computer the icon is back to default settings. I cannot save the changes and it is quite frustrating. The app was perfect before the update and I really love it, hope this can be fixed.

**Comment by soleon** [comment]
@lucaorla2000 thanks for reporting the issue. This has been discussed and resolved in #4.

Please see [my comment in the issue](https://github.com/soleon/Percentage/issues/4#issuecomment-2543127490) for some details.

Long story short, please try completely uninstalling the app and reinstalling the latest 2.1.0 version from Microsoft Store see if it resolves your issue.
