### ISSUE TITLE
Battery percentage icon is not showing in the taskbar.

### ISSUE THREAD

**Issue by Arkaghoshg** [soleon/Percentage#15]
As mentioned in the title the battery percentage icon is not showing in the taskbar. Recently I updated the application from  Microsoft Store and installed it properly. But still, the icon is not coming. Just when I'm starting my laptop a pop-up window is coming which is showing the battery details. Please fix it @soleon .
![battery %](https://github.com/user-attachments/assets/612b36fb-0508-46a0-8602-e48f95110189)
![battery details](https://github.com/user-attachments/assets/1d39b8e1-c8e3-4a37-9762-6f79ad3a910b)

**Comment by soleon** [comment]
@Arkaghoshg you should be able to see the percentage icon clicking the `^` button.

Windows 11 hides any new tray icon into this expandable area by default and there's no way to change this system behaviour. If you wish the percentage icon to always show in the tray, simply drag the icon into the tray from the expandable area.
![image](https://github.com/user-attachments/assets/71281b0a-65bb-4c87-b69a-20d6f9c1c605)

To hide the main window of the app when starting it up, turn on the "Hide at start up" option in the settings page.
![image](https://github.com/user-attachments/assets/bb9f1871-5721-4b83-a8e1-3d3ac75d0402)
