### ISSUE TITLE
Setting seems to be saved only when the app closed.

### ISSUE THREAD

**Issue by M-G-Y-Blue** [soleon/Percentage#17]
I used to change the setting and shutdown my computer without exiting the app, but the setting can not be saved everytime. Then I tried to change the setting and restart the app, and the setting saved.
This issue doesn't affect me anymore, but it may affect other new users.

**Comment by soleon** [comment]
@M-G-Y-Blue thanks for reporting the issue.

This is duplicated with issue #4 which has already been resolved.

Please update the app to the latest version in the Microsoft Store to fix this problem.
