### ISSUE TITLE
Battery Percentage Stopped Appearing

### ISSUE THREAD

**Issue by Bristlerske** [soleon/Percentage#29]
The battery percentage stopped showing up on my taskbar. This started a few weeks ago, and I believe it happened after I updated to the 24H2 version of Windows 11. I've tried deleting and reinstalling the app, but it didn't fix the issue.

**Comment by soleon** [comment]
Hi @Bristlerske can you share more details of this issue? Was there any error before the percentage icon disappeared?

Also see [my comment](https://github.com/soleon/Percentage/issues/15#issuecomment-2547449740) in issue #15 in case it is related.
