### ISSUE TITLE
Error popup

### ISSUE THREAD

**Issue by abulghoor1** [soleon/Percentage#36]
<img width="308" alt="image" src="https://github.com/user-attachments/assets/1f612ed8-2c62-42e6-93ad-c3409459deca" />

![image](https://github.com/user-attachments/assets/eabd6deb-a387-4446-b6a6-bdcd88feacd4)

**Comment by soleon** [comment]
Hi @abulghoor1 this issue is already fixed in version [2.1.4](https://github.com/soleon/Percentage/releases/tag/2.1.4). Please update the app to the latest version in Microsoft Store to solve this problem.

Closing, duplicated with issue #25.
