### ISSUE TITLE
Option to set custom color in color selector 

### ISSUE THREAD

**Issue by webdevs-pro** [soleon/Percentage#5]
After recent update to version 2.0 in the new UI I can not select white color for tray icon text.
![image](https://github.com/user-attachments/assets/29d9599e-d0a4-4901-aad2-eec6d9fad1a9)

**Comment by jasurgraduate** [comment]
It would be even better if we could be able to choose a color from color picker. I personally prefer bright colors to make it more appealing on the bottom panel.

**Comment by koreycabra** [comment]
I am also having this issue and I use this app daily. I need the white coloring for my visibility and poor eyesight.

I do not really need different notification colors, so I would just appreciate the ability set them all to white to match the rest of my system tray. Most of my UI is red, so the colors all clash and it's frustrating. I tried to turn the levels off, and still the colors remained. So please add white to the selection or add a color wheel so everyone can pick their own aesthetic.

**Comment by soleon** [comment]
@koreycabra I've added black and white colours in version [2.0.9](https://github.com/soleon/Percentage/releases/tag/2.0.9). This version will be available in Microsoft Store soon.

There is no good colour picker that fits a modern fluent UI style. I'm planning to create one myself, but I can't give any concrete estimates on when this will be available.

**Comment by webdevs-pro** [comment]
White or black to match the Windows theme is sufficient. Thanks!
