### ISSUE TITLE
Battery Percentage in system tray does not report correctly.

### ISSUE THREAD

**Issue by leckert123** [soleon/Percentage#56]
Latest version 2.1.5.0 

The battery is fully charged yet the display shows 67%. When I open details, it correctly shows 100% as does Win11's battery status, but the system tray icon remains at 67.

![image](https://github.com/user-attachments/assets/a827d15d-5bf7-4981-b056-bc8ae8dd9431)
![image](https://github.com/user-attachments/assets/fda1bc14-7237-430a-9297-1b3ba12a09ce)
![image](https://github.com/user-attachments/assets/9b5b4ddf-852d-404b-bfb6-9a94682eff52)

**Comment by leckert123** [comment]
When it was updated from 2.1.5.0 to 2.1.6.0 it initially seemed like the bug was squished.  It's not. Laptop was unplugged from the charger, run for a little while, then plugged back in.  10-15 minutes later, after charging, the icon was still stuck at 94%, while Details for the app shows 100% fully charged and Windows reports 100% as well.

**Comment by leckert123** [comment]
When it was updated from 2.1.5.0 to 2.1.6.0 it initially seemed like the bug was squished.  It's not. Laptop was unplugged from the charger, run for a little while, then plugged back in.  10-15 minutes later, after charging, the icon was still stuck at 94%, while Details for the app shows 100% fully charged and Windows reports 100% as well.

**Comment by medic17** [comment]
@leckert123 Did you lock, hibernate or sleep the device when this happened?

**Comment by soleon** [comment]
This seems to be the same issue as #55. Closing.

**Comment by leckert123** [comment]
The laptop did NOT hibernate, sleep, or lock when this occurred.  It was unplugged from power, being used on power briefly, which consumed some battery capacity, and then plugged back in. When plugged back in, the displayed value of the icon remained stuck at the discharged value in yellow, which indicated that the tray icon thought it was still on battery power.

Last night, it dropped to 92%, and was plugged back in overnight. and lid closed.  After overnight, it's still at 92%, but displayed green, as it's plugged in, and obviously at 100% fully charged.

**Comment by leckert123** [comment]
The laptop did NOT hibernate, sleep, or lock when this occurred.  It was unplugged from power, being used on power briefly, which consumed some battery capacity, and then plugged back in. When plugged back in, the displayed value of the icon remained stuck at the discharged value in yellow, which indicated that the tray icon thought it was still on battery power.

Last night, it dropped to 92%, and was plugged back in overnight. and lid closed.  After overnight, it's still at 92%, but displayed green, as it's plugged in, and obviously at 100% fully charged.

This is interesting. I've unplugged it and it's still showing green (charging/plugged in) at 92%, but the details show 94%. It seems like something just causes the tray icon to get stuck at some value.
![image](https://github.com/user-attachments/assets/0e2929dd-d711-4286-beed-145dd0810708)

**Comment by leckert123** [comment]
If I exit the app (right click --> exit) and open it again from the MS Store, it shows the current value. Somehow it seems the icon is not being refreshed although the app itself it doing so

**Comment by leckert123** [comment]
If I exit the app (right click --> exit) and open it again from the MS Store, it shows the current value. Somehow it seems the icon is not being refreshed although the app itself it doing so.

I have narrowed one cause down to a specific sequence. When the laptop is unplugged, it works fine.  When the laptop is plugged in to charge, the icon color changes from battery to charging mode, but it stops counting up as the battery % increases.
