### ISSUE TITLE
Add setting to change tray icon font size

### ISSUE THREAD

**Issue by regice202** [soleon/Percentage#6]
As stated in the title, I'm unable to scale the font of the tray icon.. This is apparently (and definitely should be) an intended feature which isn't currently present.. Please add/fix this!!! @soleon

![Percentage App_WtwYCdDwtk](https://github.com/user-attachments/assets/4f741e7f-e79d-40c1-87f8-7d35cb8a0ad8)

**Comment by regice202** [comment]
In addition, apparently the font gets stretched when the power is low enough.. Looks terrible.. please fix! @soleon 

![image](https://github.com/user-attachments/assets/8270d08b-4c5f-4564-bd79-65a837592f98)

**Comment by soleon** [comment]
@regice202 thanks for reporting this issue.

The font size option was removed on purpose from the previous major version 1.x due to the new rendering method of the tray icon in version 2.

Windows limits the tray icon to a 16 x 16 pixel square. I've tuned the text display in the icon to be the maximum size it can contain in its allowed area. I'd like to know your use case of changing the font size.

I can't reproduce the stretching issue when the battery is at a single digit capacity. Do you mind sharing the font family you had set in the app, your Windows display scaling setting and accessibility text size setting?
![image](https://github.com/user-attachments/assets/53492fad-c88e-4268-a178-9eea4269ce45)

**Comment by regice202** [comment]
@soleon So the font was just the default font that's loaded upon install (after it updated for me from MS store); Microsoft San Serif. I haven't touched the accessibility scaling, although my screen is scaled to 200% since I'm on a Surface Pro 8 (2k display). I also have ExplorerPatcher which might be messing with it a little bit.. But every other application I have in the tray has no issue with it.. Thanks again for the response, hopefully you can fix it soon! :)

**Comment by soleon** [comment]
@regice202 Thanks for providing the details.

I've tried installing [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) and scaling my UI to 200% on a 2K screen with 1920x1200 resolution (Dell XPS). Even tried manually enabling the hidden registry key to turn on "tablet mode" in Windows 11 `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\PriorityControl\ConvertibleSlateMode` with no success to reproduce this issue.

I may need to source a Surface Pro device to further investigate this but there's no guarantee when I will be able to obtain the device anytime soon.

**Comment by mark-r-7** [comment]
I’d like to second the request for the ability to adjust the font size. I'm interested not in making the font size any larger, but rather smaller. Before the Fluent UI update, I would reduce the size of the text to more closely match the size of the date and time.

I’ve attached a screenshot to illustrate how the current size appears a bit too large on my end. Adding an option to scale down the text would be helpful.

![Screenshot 2024-12-22 205813](https://github.com/user-attachments/assets/11ccf283-2bc9-486c-9456-d7a8b4b653be)

**Comment by soleon** [comment]
I have release version [2.1.3](https://github.com/soleon/Percentage/releases/tag/2.1.3) with the setting to change the tray icon font size. It should be available in the Microsoft Store already.

![image](https://github.com/user-attachments/assets/035e0131-b257-4237-98c3-73d199f1b18e)

Note that the tray icon region is limited by Windows system itself so if you set the font size to too large, it gets cut off by the system like this:

![image](https://github.com/user-attachments/assets/866e4fd4-255b-4536-8edf-70d7c79aecb6)
