### ISSUE TITLE
"Hide at Startup" setting not persisting

### ISSUE THREAD

**Issue by scrutiny6239** [soleon/Percentage#9]
The app window keeps reopening on startup despite activating the "Hide at Startup" toggle. When I check the settings after each restart, I find that the toggle reverted back to off.
![image](https://github.com/user-attachments/assets/7dfb7abc-6bed-49dd-be43-9cb49e1b366c)

**Comment by regice202** [comment]
This applies to all settings apparently. I also changed the Low Battery color, and hide menu setting. Didn't persist after restart.

**Comment by sjia2s** [comment]
I downloaded .NET 9.0 and it's not an issue for me; the app keeps all my settings (except the notification toggles though)

**Comment by regice202** [comment]
Just downloaded .NET 9.0, hopefully that fixes it!

**Comment by soleon** [comment]
This is duplicated with issue #4. Closing this.
